name: Build and deploy JAR app to Azure Web App - gccc-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Actualizat la versiunea 4

      - name: Set up Java version
        uses: actions/setup-java@v4  # Actualizat la versiunea 4, compatibilă cu Node.js 20
        with:
          distribution: 'temurin'  # Recomandat pentru JDK
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  # Actualizat la versiunea 4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Necesită pentru solicitarea JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4  # Actualizat la versiunea 4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v1  # Verifică să fie cea mai recentă versiune
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6DD30F163BB840F798BD2386A6BFA882 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B9551A2F73C44A5AA6B3B3ACCFFC0C74 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0DC5D8F13E004E71A470D0D3EF3C8A84 }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2  # Verifică să fie cea mai recentă versiune
        with:
          app-name: 'gccc-1'
          slot-name: 'Production'
          package: '*.jar'
